// src/services/api/marketplace/marketplaceApi.js
import axiosInstance from '@/services/axiosConfig';
import { envConfig } from '@/config/environment';

class MarketplaceApi {
    constructor() {
        this.baseUrl = envConfig.getApiUrl('/marketplace');
    }

    async errorHandler(apiCall) {
        try {
            const response = await apiCall();
            return response.data;
        } catch (error) {
            console.error('Marketplace API Error:', error);
            // Transform backend errors into user-friendly messages
            if (error.response?.data?.detail) {
                throw new Error(error.response.data.detail);
            }
            throw new Error(error.message || 'Something went wrong');
        }
    }

    // Strategy Pricing Methods
    async getStrategyPricing(strategyToken) {
        return this.errorHandler(() => 
            axiosInstance.get(`${this.baseUrl}/strategies/${strategyToken}/pricing`)
        );
    }

    async createStrategyPricing(pricingData) {
        return this.errorHandler(() => 
            axiosInstance.post(`${this.baseUrl}/webhook-pricing`, pricingData)
        );
    }

    async updateStrategyPricing(pricingId, pricingData) {
        return this.errorHandler(() =>
            axiosInstance.put(`${this.baseUrl}/webhook-pricing/${pricingId}`, pricingData)
        );
    }

    // Rating Method - works for both webhook and engine strategies
    async rateStrategy(sourceId, rating) {
        console.log('Rating strategy:', { sourceId, rating });
        return this.errorHandler(() =>
            axiosInstance.post(
                `${this.baseUrl}/strategies/${sourceId}/rate`,
                { rating: parseInt(rating) },
                {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }
            )
        );
    }

    // Purchase Methods
    async purchaseStrategy(strategyToken, purchaseData) {
        return this.errorHandler(() => 
            axiosInstance.post(`${this.baseUrl}/strategies/${strategyToken}/purchase`, purchaseData)
        );
    }

    async subscribeToStrategy(strategyToken, subscriptionData) {
        return this.errorHandler(() => 
            axiosInstance.post(`${this.baseUrl}/strategies/${strategyToken}/subscribe`, subscriptionData)
        );
    }

    // Quick purchase for the beautiful UI (auto-determines purchase type)
    async quickPurchase(strategy, options = {}) {
        const { 
            startTrial = false,
            billingInterval = 'monthly',
            paymentMethodId = null // Will be generated by Stripe Elements
        } = options;

        const pricing = strategy.pricing;
        
        if (!pricing || pricing.pricingType === 'free') {
            // For free strategies, just "follow" them
            return this.followFreeStrategy(strategy.token);
        }

        // For paid strategies, determine purchase type
        if (pricing.pricingType === 'subscription') {
            return this.subscribeToStrategy(strategy.token, {
                payment_method_id: paymentMethodId,
                billing_interval: billingInterval,
                start_trial: startTrial || (pricing.isTrialEnabled && pricing.trialDays > 0)
            });
        }

        if (pricing.pricingType === 'one_time') {
            return this.purchaseStrategy(strategy.token, {
                payment_method_id: paymentMethodId,
                start_trial: false
            });
        }

        throw new Error('Unsupported pricing type');
    }

    // For free strategies - follow without payment
    async followFreeStrategy(strategyToken) {
        // This would use the existing webhook API to subscribe to free strategies
        const webhookApi = await import('@/services/api/Webhooks/webhookApi');
        return webhookApi.webhookApi.subscribeToStrategy(strategyToken);
    }

    // Enhanced marketplace listing with pricing info
    async getMarketplaceStrategies(filters = {}) {
        const params = new URLSearchParams();
        
        if (filters.category) params.append('category', filters.category);
        if (filters.pricingType) params.append('pricing_type', filters.pricingType);
        if (filters.minPrice) params.append('min_price', filters.minPrice);
        if (filters.maxPrice) params.append('max_price', filters.maxPrice);
        if (filters.hasFreeTrial) params.append('has_trial', filters.hasFreeTrial);
        if (filters.creatorTier) params.append('creator_tier', filters.creatorTier);

        return this.errorHandler(() => 
            axiosInstance.get(`${this.baseUrl}/strategies/available?${params.toString()}`)
        );
    }

    // Get user's purchases and subscriptions
    async getUserPurchases() {
        return this.errorHandler(() => 
            axiosInstance.get(`${this.baseUrl}/my-purchases`)
        );
    }

    // Check if user has access to a specific strategy
    async checkStrategyAccess(strategyToken) {
        return this.errorHandler(() => 
            axiosInstance.get(`${this.baseUrl}/strategies/${strategyToken}/access`)
        );
    }

    // Verify purchase session after Stripe checkout
    async verifyPurchaseSession(sessionId) {
        return this.errorHandler(() => 
            axiosInstance.get(`${this.baseUrl}/verify-purchase-session/${sessionId}`)
        );
    }

    // Cancel subscription
    async cancelSubscription(purchaseId) {
        return this.errorHandler(() => 
            axiosInstance.post(`${this.baseUrl}/subscriptions/${purchaseId}/cancel`)
        );
    }

    // Trial conversion (when trial period ends)
    async convertTrialToSubscription(purchaseId, paymentMethodId) {
        return this.errorHandler(() => 
            axiosInstance.post(`${this.baseUrl}/purchases/${purchaseId}/convert-trial`, {
                payment_method_id: paymentMethodId
            })
        );
    }
}

// Create singleton instance
export const marketplaceApi = new MarketplaceApi();
export default marketplaceApi;